env:
    node: true
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:vue/vue3-recommended
    - '@vue/airbnb'
    - prettier

parser: vue-eslint-parser
overrides: []
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - vue
rules: { 'vue/multi-word-component-names': 'off' }
